### ISSUE TITLE
Host opcode ProcessEvents missing

### ISSUE THREAD

**Issue by Boscop** [overdrivenpotato/rust-vst2#13]
VST plugins that send MIDI events use the host opcode audioMasterProcessEvents (8) as described here:
http://www.asseca.org/vst-24-specs/amProcessEvents.html
http://www.asseca.org/vst-24-specs/amCallbacks.html

But this opcode is missing from rust-vst2, it should be here in host.rs after GetTime:
https://github.com/overdrivenpotato/rust-vst2/blob/82a60b5c13e425e5ef4c30338f7eaaec179e14b5/src/host.rs#L42
As it is now, because of the missing opcode, all following opcodes have the wrong numerical representation, they are one less than they should be, e.g. IOChanged is 12 but should be 13 etc.

**Comment by overdrivenpotato** [comment]
Should be fixed by 69488687b05858da09bdb2dfef68e7fdc6c78bf5. Nice catch, thanks!
