### ISSUE TITLE
Add write access contributors to help maintain rust-vst2

### ISSUE THREAD

**Issue by piedoom** [overdrivenpotato/rust-vst2#38]
This is an awesome repo for developing VSTs with Rust.  However, the last merged PR was 1 month ago despite fairly active development on forks.  I understand that other work often comes up, and it's hard to get to everything in a short period of time.

To help with that, I would ask that you give someone like @Boscop or @zyvitski write access to the repository so merges and issues can be resolved more quickly.

**Comment by zyvitski** [comment]
I would not be opposed to this responsibility, though I have a feeling that @Boscop is probably more knowledgeable about this project and may be the better choice in terms of making sure that any proposed changes will be for the benefit of the project.

**Comment by conundrumer** [comment]
For any newcomers, we have a hard fork of this repo over here: https://github.com/rust-dsp/rust-vst
